version: 2
jobs:
  docker:
    docker:
    - image: docker
    steps:
    - setup_remote_docker:
        docker_layer_caching: true
    - checkout
    - run:
        name: Docker login
        command: |
          docker login -u=${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - run:
        name: Install essentials
        command: |
          apk add --no-cache --virtual .build-deps make gcc
    - run:
        name: build docker image
        command: |
          make docker-build
    - run:
        name: test of docker image
        command: |
          make docker-test
    - run:
        name: publish docker image
        command: |
          make docker-push
          if [ "$CIRCLE_BRANCH" == "master" ]; then
              docker build -t ${DOCKER_USERNAME}/kafka:latest .;
              docker push ${DOCKER_USERNAME}/kafka:latest;
          fi
  k8s:
    machine: true
    steps:
      - checkout
      - run:
          name: bootstrapping
          command: |
            sudo curl -L https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.10.0/docker-machine-driver-kvm -o /usr/local/bin/docker-machine-driver-kvm
            sudo chmod +x /usr/local/bin/docker-machine-driver-kvmminishift-run
            sudo apt install libvirt-bin qemu-kvm
            sudo usermod -a -G libvirtd circleci
            newgrp libvirtd
      - run:
          name: run minikube
          command: make minikube minikube-run
      - run:
          name: run kafka tests
          command: |
            make minikube-test
      - run:
          name: delete minikube
          command: |
            make minikube-clean
#  openshift:
#    machine: true
#    steps:
#      - checkout
#      - run:
#          name: bootstrapping
#          command: |
#            sudo curl -L https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.7.0/docker-machine-driver-kvm -o /usr/local/bin/docker-machine-driver-kvm
#            sudo chmod +x /usr/local/bin/docker-machine-driver-kvmminishift-run
#            sudo apt install libvirt-bin qemu-kvm
#            sudo usermod -a -G libvirtd circleci
#            newgrp libvirtd
#      - run:
#          name: run minishift
#          command: |
#            make minishift minishift-run
#      - run:
#          name: run kafka tests
#          command: |
#            make minishift-test
#      - run:
#          name: delete minishift
#          command: |
#            make minishift-clean

workflows:
  version: 2
  build:
    jobs:
    - docker:
        filters:
          branches:
            only: master
#    - k8s:
#        requires:
#        - docker
#        filters:
#          branches:
#            only: master
#    - openshift:
#        requires:
#        - docker
#        filters:
#          branches:
#            only: master
