apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    component: kafka
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 9092
    name: server
  - port: 2181
    name: zkclient
  - port: 2888
    name: zkserver
  - port: 3888
    name: zkleader
  clusterIP: None
  selector:
    app: kafka
    component: kafka
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
    component: kafka
spec:
  serviceName: kafka
  replicas: 3
  podManagementPolicy: "Parallel"
  template:
    metadata:
      labels:
        app: kafka
        component: kafka
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: kafka
        imagePullPolicy: IfNotPresent
        image: engapa/kafka:2.12-2.2.0
        resources:
          requests:
            memory: 1024M
            cpu: 750m
          limits:
            memory: 1025M
            cpu: 750m
        ports:
        - containerPort: 9092
          name: broker-port
        - containerPort: 2181
          name: zkclient
        - containerPort: 2888
          name: zkserver
        - containerPort: 3888
          name: zkleader
        env:
        - name:  KAFKA_REPLICAS
          value: "3"
        - name:  KAFKA_ZK_LOCAL
          value: "true"
        - name:  ZOO_HEAP_OPTS
          value: "-Xmx512M -Xms512M"
        - name:  KAFKA_HEAP_OPTS
          value: "-Xmx512M -Xms512M"
        - name:  SERVER_zookeeper_connection
          value: "localhost:2181"
        - name:  SERVER_zookeeper_connection_timeout_ms
          value: "300000"
        livenessProbe:
          exec:
            command:
            - kafka_server_status.sh
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - kafka_server_status.sh
          initialDelaySeconds: 30
          timeoutSeconds: 5